### ISSUE TITLE
problems plotting out the raster

### ISSUE THREAD

**Issue by dieza** [BigelowLab/nearth#1]
Hi,
Thanks for the package.
When trying to reproduce your example I got an error
raster::plotRGB(r)
Error in (function (classes, fdef, mtable)  : 
  unable to find an inherited method for function ‘plotRGB’ for signature ‘"list"’
It seems to me that all is correct "r" is a list containing a RasterBrick
> r
$NE1_50M_SR_W
class       : RasterBrick 
dimensions  : 5400, 10800, 58320000, 3  (nrow, ncol, ncell, nlayers)
resolution  : 0.03333333, 0.03333333  (x, y)
extent      : -180, 180, -90, 90  (xmin, xmax, ymin, ymax)
coord. ref. : +proj=longlat +datum=WGS84 +no_defs +ellps=WGS84 +towgs84=0,0,0 
data source : /Users/adiez/Downloads/OB_50M/NE1_50M_SR_W.tif 
names       : NE1_50M_SR_W.1, NE1_50M_SR_W.2, NE1_50M_SR_W.3 
min values  :              0,              0,              0 
max values  :            255,            255,            255 

sessionInfo()
R version 3.3.1 (2016-06-21)
Platform: x86_64-apple-darwin13.4.0 (64-bit)
Running under: OS X 10.9.5 (Mavericks)

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] rgdal_1.1-10    nearth_0.1      raster_2.5-8    sp_1.2-3       
[5] devtools_1.12.0

loaded via a namespace (and not attached):
 [1] Rcpp_0.12.7     lattice_0.20-34 digest_0.6.10   withr_1.0.2    
 [5] grid_3.3.1      R6_2.1.3        git2r_0.15.0    httr_1.2.1     
 [9] curl_1.2        tools_3.3.1     rgeos_0.3-20    memoise_1.0.0  
[13] knitr_1.14

**Comment by btupper** [comment]
Good catch!

The readme documentation was in error.  When using `read_nearth()` the returned value is a list (or `NULL`) which permits you to request more than one data set at a time.  

I also found namespace issues the wonderful `devtools::check()` function helped me figure out.  

The updated docs show how to run the example correctly now.  Thanks for the heads up and the very clear example.
